### ISSUE TITLE
Manglende tillit på mellomliggende CA og Commfides sin sertifikatkjede.

### ISSUE THREAD

**Issue by aberner** [digipost/signature-api-specification#11]
ref. README.md og "og legger til Buypass sitt rotsertifikat i truststore (det serveren skal identifisere seg med)."

Her referes det kun til Buypass og ikke Commfides. Det har vel sin årsak i at Posten har kjøpt sertifikat fra Buypass. 
Anbefaler at dokumentasjonen legger opp til at alle tjenesteeiere legger til både Buypass og Commfides sitt rotsertifikat, slik at tjenesten kan benytte sertifikater fra begge leverandører.

Er det ikke slik at det også må legges inn mellomliggende sertifikater fra Buypass/Commfides i cacerts for å sikre at man får tillit til hele sertifikatkjeden og for å begrense det til tillit til buypass/commfides sine CA som utsteder virksomhetssertifikater. Rot-CA'n utsteder via andre mellomliggende CA'r også andre sertifikater som ikke har samme sertifikatpolicy og dermed ikke skal stoles på.

**Comment by lillesand** [comment]
Takk for meldingen. Jeg legger inn en utviklingsoppgave på å finne ut hvilke trust anchors vi skal bruke og å legge inn disse :+1:

**Comment by lillesand** [comment]
Har pekt dokumentasjonen til det som står om virksomhetssertifikater for digital post. Mulig vi har samme avveiningen om vi vil linke eller kopiere dokumentasjon som i #16.

**Comment by lillesand** [comment]
Når det gjelder det andre spørsmålet ditt: har det egentlig noen verdi å legge inn intermediate-sertifikatene i truststore? Så lenge vi legger inn rotsertifikatet så kan klienten autentisere seg med å legge til en full sertifikatkjede opp til rota.

Gitt følgende sertifikatkjede:
```
    A
  /    \
B     C
          \
          D
```

Hvis vi har tillit til sertifikatene A og B vil serveren akseptere en autentisering basert på sertifikatkjeden D-C-A, fordi den treffer tillitsankeret A.

Jeg ser vi legger inn intermediate-sertifikatene i truststore i SDP, men jeg er ikke sikker på hvilken effekt det har. Det kan godt tenkes at det er noe jeg har misforstått her.

**Comment by aberner** [comment]
Usikker på den fremstillingen du viser til. Tar vi eksempelet ditt så tror jeg det vi ønsker er at vi kun stoler på sertifikatkjeden D-C-A, der C og A er lagt inn eksplisitt i lokale truststores. Mens sertifikater utstedt under B ikke skal stoles på selv om vi stoler på A.

Tar vi Buypass som eksempel så utsteder Buypass sin Rot-CA forskjellige typer sertifikater, ikke bare virksomhetssertifikater. ref: http://www.buypass.no/26553/overgang-til-ny-ca-struktur-for-qc-og-vid-4.februar-2013

Nå kan du vel si at vi ikke vil komme til å stole på SSL sertifikater fordi de ikke vil inneholde et org.nummer. 
Det vi egentlig stoler på er en eksplisitt sertifikatpolicy hos Buypass med OID 2.16.578.1.26.1.3.2 og tilsvarende hos Commfides. 
ref. https://www.buypass.no/kundeservice/nedlastingssenter/_attachment/26270?_ts=1505bfe4d20
https://www.buypass.no/kundeservice/nedlastingssenter (se under CA dokumentasjon (juridisk))

Så jeg mener vel at tjenesten bør ha eksplisitt tillit til den utstedende CA'en og ikke bare Rot-CA.

**Comment by lillesand** [comment]
Hvis vi tar utgangspunkt i Buypass sine sertifikater:
<img src="http://www.buypass.no/forside/_image/34548/label/large.jpeg">

Hvis vi putter `BP Cl3 Rot CA` i truststoren, men bare skal stole på sertifikater som er utstedt av `BP Cl3 CA 3`, så vil det kreve at vi gjør en sjekk om at klientsertifikatet er utstedt av `BP Cl3 CA 3` – selv om det har en gyldig sertifikatkjede opp `BP Cl3 Rot CA`. Etter min forståelse vil det gi samme funksjonalitet som å bare putte `BP Cl3 CA 3` i truststore.

Enig med deg i at jeg tror dette ikke kommer til å få noen stor praktisk betydning, men jeg har lyst til å være sikker på at vi har lik forståelse av hvordan dette skal være.

**Comment by aberner** [comment]
For å følge standarden skal du vel verifisere gyldigheten av alle sertifikater i kjeden. både BP Cl3 CA 3 og BP Cl3 Rot CA individuelt. Men dette er vel mest teori.
Dersom sertifikatvalideringen funger ok med å legge BP Cl3 CA 3 i truststore kan nok det være en praktisk løsning.

**Comment by lillesand** [comment]
Du har rett. Det blir feil å validere en sertifikatkjede som ikke ender i et selfsigned (altså rot) sertifikat. Takk for tålmodigheten mens jeg fikk jobbet meg gjennom det :smile:. 

Koden skal være riktig, skal sikre at dokumentasjonen er det i morgen :+1:

**Comment by lillesand** [comment]
… i en litt raus definisjon av "i morgen" :wink:
