### ISSUE TITLE
Feilmelding: Unsupported Media Type (#415)

### ISSUE THREAD

**Issue by Sigurhan** [digipost/signature-api-specification#117]
Hei

forsøker å sette opp den initielle POSTen for å opprette signeringsoppdrag, men får bare følgende feilmelding: «Unsupported Media Type (#415)». Hva skyldes dette? Nedenfor er et utsnitt fra Raw-loggen fra Fiddler når jeg forsøker å kjøre testen.

Content-Length: 59741
Expect: 100-continue
Accept-Encoding: gzip, deflate
 
Content-Type: multipart/form-data; boundary=21ac6e6722fc4c74b0ab2430299b9f7e
 
--21ac6e6722fc4c74b0ab2430299b9f7e
Content-Disposition: form-data; name="Request"
Content-Type: application/xml
 
<ns2:portal-signature-job-request xmlns:ns2="http://signering.posten.no/schema/v1"><ns2:reference>Test-reference</ns2:reference></ns2:portal-signature-job-request>
--21ac6e6722fc4c74b0ab2430299b9f7e
Content-Disposition: form-data; name="Dokumentpakken"
Content-Type: application/octet-stream

**Comment by asjafjell** [comment]
Heisann! Bruker du klientbiblioteket eller har du lagd din egen integrasjon?

**Comment by Sigurhan** [comment]
Dette er en egen integrasjon.

**Comment by asjafjell** [comment]
Beklager at vi ikke har fått  gitt deg et svar enda. Vi skal se på det så raskt som det lar seg gjøre. Har du kommet videre eller har du fortsatt samme problem?

**Comment by Sigurhan** [comment]
Har fortsatt samme problem.

**Comment by asjafjell** [comment]
Da skal jeg få prioritert denne øvert og ser på den i dag.

**Comment by asjafjell** [comment]
Etter litt mye om og men klarte vi å få ut logging fra vårt eget klientbibliotek:

Følgende er utgående request for oppretting av oppdrag:

```
2019/03/06 14:11:12.034|DEBUG|Outgoing: 
Method: POST, https://api.test.signering.posten.no/api/988015814/direct/signature-jobs 
Accept: application/xml 
User-Agent: digipost-signature-api-client-dotnet/0.0.0.0,(netcore/2.1.4) 
Content-Type: multipart/mixed; boundary=b3e3e314-c83b-4455-8866-14501a67e20c 
<?xml version="1.0" encoding="utf-8"?><direct-signature-job-request xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://signering.posten.no/schema/v1"><reference>Reference</reference><exit-urls><completion-url>http://localhost/completion</completion-url><rejection-url>http://localhost/cancellation</rejection-url><error-url>http://localhost/error</error-url></exit-urls><status-retrieval-method>WAIT_FOR_CALLBACK</status-retrieval-method></direct-signature-job-request> 
```

Og responsen er da:
```
2019/03/06 14:11:12.784|DEBUG|Incoming: 
StatusCode: 200, OK 
Date: Wed, 06 Mar 2019 13:11:12 GMT 
Cache-Control: no-store, no-transform, no-cache 
Content-Type: application/xml 
Content-Length: 663 
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><ns4:direct-signature-job-response xmlns="http://uri.etsi.org/01903/v1.3.2#" xmlns:ns2="http://www.w3.org/2000/09/xmldsig#" xmlns:ns3="http://uri.etsi.org/2918/v1.2.1#" xmlns:ns4="http://signering.posten.no/schema/v1"><ns4:reference>Reference</ns4:reference><ns4:signature-job-id>13118</ns4:signature-job-id><ns4:redirect-url signer="01048200229">https://test.signering.posten.no/signere/#/-/UdX-CvBMJswcIL4F2DAmjE2GnEoEGSRT3_2oYjVNSqU</ns4:redirect-url><ns4:status-url>https://api.test.signering.posten.no/api/988015814/direct/signature-jobs/13118/status</ns4:status-url></ns4:direct-signature-job-response> 
 |Digipost.Signature.Api.Client.Core.BaseClient|
2019/03/06 14:11:13.443|DEBUG|Successfully created Direct Job with JobId: 13118. |Digipost.Signature.Api.Client.Direct.DirectClient|
```

Jeg har ikke fått diffet det mot det du har postet, men da har du et godt utgangspunkt for å sjekke dette selv.

**Comment by boguszjelinski** [comment]
jeg hadde samme problemet så litt om løsningen :) jeg  har brukt Apache http Client, ikke RestTemplate:  

HttpEntity entity = MultipartEntityBuilder.create()
            .setMimeSubtype("mixed")
            .addPart(FormBodyPartBuilder.create()
                .setName("file")
                .setBody(new StringBody(meta, ContentType.create("application/xml")))
                .build())
            .addPart(FormBodyPartBuilder.create()
                .setName("file")
                .setBody(new ByteArrayBody(zip, "file"))
                .build())
            .build();
        HttpPost request = new HttpPost(difiUrl);
        request.setEntity(entity);
        HttpClient client = HttpClientBuilder.create().build();
        HttpResponse resp = client.execute(request);

Og pass på at man oppretter META-INF mappe noen linjer før man lagrer signatures.xml ellers får man 400 fra Difi (selv om unzip ville produsere samme filer/mapper; bug i java.util.zip? ):
 zip.putNextEntry(new ZipEntry("META-INF/"));
            zip.putNextEntry(new ZipEntry("manifest.xml"));
            zip.write(manifest.getBytes());
            zip.putNextEntry(new ZipEntry("document.pdf"));
            zip.write(pdf);
            zip.putNextEntry(new ZipEntry("META-INF/signatures.xml"));
            zip.write(Base64.getDecoder().decode(signaturesB64));
lett å se at jeg gir meta.xml som String, pdf som byte[] og signatures.xml får jeg Base64encoded fra min HSM.

**Comment by simenstoa** [comment]
Hei, @Sigurhan! Fikk du løst problemet?

**Comment by Sigurhan** [comment]
@simenstoa Hei! Nei, fant ikke ut av det, og prosjektet ble samtidig lagt på is. Mulig det blir aktuelt å plukke opp tråden igjen i fremtiden. Takk for svar uansett!
