### ISSUE TITLE
Eldre versjon - PortalClient.GetStatusChange() "dør".

### ISSUE THREAD

**Issue by Trondelond** [digipost/signature-api-specification#124]
Hei, ble henvist hit fra Sture Føre, vi har et litt underlig problem.

I noen dager har vår tjeneste (benytter digipost-signature-api-client v3.0.1) pollet avgårde med en feil i sertifikat. Sertifikat er nå korrigert, men vi ser at PortalClient.GetStatusChange() rett og slett kjører og forsvinner i løse luften for oss. 

Dette er en tjeneste som kjører for flere organisasjoner, og alle andre ser ut til å fungere ok. Så jeg lurer på om man kan oppleve å bli stoppet i døra på et vis for et gitt organisasjonsnummer etter for mange feilforespørsler, eller om det er noen andre tips til feilsøking her.
Tidligere fikk vi melding tilbake om at TLS ikke kunne opprettes, men nå skjer det som nevnt "ingenting" når metoden kalles for denne organisasjonen.

Sertifkat er tilsynelatende OK, med "Digital Signature" i Key Usage.

Jeg ser https://github.com/digipost/signature-api-specification/issues/39 foreslås her på github, og jeg anser det ikke som usannsynlig at det fremdeles er noe galt med sertifikat, men i og med at jeg ikke får noen melding tilbake velger jeg å legge inn et issue her.

Mvh
Trond

**Comment by asjafjell** [comment]
Heisann! Takk for lang og god informasjon om hva du opplever. Hva er grunnen til at du lukket issuet?

**Comment by Trondelond** [comment]
Hei, det var rett og slett usikkerhet om hvor det burde ligge, men for all del - jeg skal ikke nekte deg å svare om du har et innspill :)

Er det en sjekkliste vi kan benytte utover det åpenbare rundt key usage som vi kan benytte for å avdekke problemet, eventuelt sikre oss ved bestilling av sertifikater for at dette ikke skjer igjen?

Jeg antar det ikke vil hjelpe å oppgradere klienten heller, siden sertifikatet vil være det samme?

**Comment by asjafjell** [comment]
Akkurat. Du har postet det samme flere steder. Det er litt forvirrende. Hvis dette hører til dotnet-klienten, så er det det som bør holdes åpent. Lukker denne jeg, og så kan vi poste videre der.
