### ISSUE TITLE
Beskrivelse av ASiC profil og eventuelle begrensninger tjenesten setter

### ISSUE THREAD

**Issue by aberner** [digipost/signature-api-specification#16]
Det står dokumentert:

"Dokumentpakken i Posten Signering er basert på ASiC-E standarden"
Denne standarden har flere profiler og ikke alt i standarden er obligatorisk.

Det er dermed behov for å spesifisere ytterligere her hvilken profil og eventuelle begrensninger som er definert i bruken av ASiC.

Det er mulig å se til de spesifiseringene som er gjort i forbindelse med digital post: http://begrep.difi.no/SikkerDigitalPost/1.2.1/forretningslag/Sikkerhet/ kapittel om Integritet.

**Comment by lillesand** [comment]
Vi bruker samme profil, så da er det kanskje like greit å bare linke dit, @aberner?

Mulig vi bør kopiere over dokumentasjonen i tilfelle de to løsningene mot formodning divergerer over tid.

**Comment by aberner** [comment]
på siden til digital post så beskrives også krypteringsalgoritmer, så jeg er litt usikker på hva som er beste løsning. Foreløpig tror jeg det beste vil være å kopiere teksten. (uff... det var vondt å skrive).

**Comment by lillesand** [comment]
Ja, ser at det fort kan bli litt forvirrende.

Tenker dere å ta inn signeringstjenesten på begrep.difi.no på sikt? I så fall kan profilbeskrivelsen for ASiC-E etterhvert trekkes ut som felles.

Kan det være ok å linke, men at vi spesifiserer at det er det som står under overskriften "Integritet"? Det gjøres det kanskje lettere hvis/når det skal lages dokumentasjon på begrep.difi.no. Hvis du synes det heller bør kopieres så gjør jeg det!

**Comment by lillesand** [comment]
Merget den nye dokumentasjonen til master nå :+1:
