### ISSUE TITLE
Verification failed for property SigningCertificate

### ISSUE THREAD

**Issue by eikybreaky** [digipost/signature-api-specification#163]
Hei, eg får feilmelding på feltet SigningCertificate i fila signatures.xml i dokumentpakken min. Eg bruker endepunkt i test api: api.difitest.signering.posten.no/api/958284837/direct/signature-jobs. Dette er ein egen integrering i direkte flyt.

Eg har sjekket data i elementet og fulgt dokumentasjon for å generere det. Elementet CertDigest->ns2:DigestValue er ein sha1 digest av kun klient sertifikatet mitt i DER format omgjort til base64. På samme måte som gjort i eksempel pakken [her](https://signering-docs.readthedocs.io/en/latest/egen-integrasjon/dokumentpakke.html).
Elementet IssuerSerial->ns2:X509SerialNumber er organisasjonsnummeret vårt.
Elementet IssuerSerial->ns2:X509SerialName er subject fra client certifikatet vårt.

Jeg greier ikkje å sjå kva eg har gjort galt i SigningCertificate elementet. 
Kan nokon veilede meg inn på rett sti?

**Response frå api:**
`HTTP/1.1 400 Bad Request
Date: Mon, 15 Jun 2020 10:45:50 GMT
Content-Type: application/xml
Cache-Control: no-cache, no-store, no-transform
Content-Length: 683

<?xml version="1.0" encoding="UTF-8" standalone="yes"?><ns4:error xmlns="http://uri.etsi.org/01903/v1.3.2#" xmlns:ns2="http://www.w3.org/2000/09/xmldsig#" xmlns:ns3="http://uri.etsi.org/2918/v1.2.1#" xmlns:ns4="http://signering.posten.no/schema/v1"><ns4:error-code>ASICE_VALIDATION_FAILED</ns4:error-code><ns4:error-message>Error when valicating ASiCE: Verification of XAdES signature failed. [Error='Verification failed for property 'SigningCertificate': Couldn't find a reference to the signing certificate 2.5.4.5=#1309393538323834383337,CN=SIMIKS,OU=zpirit,O=SUNNHORDLAND INTERKOMMUNALE MILJØVERK IKS,C=NO']</ns4:error-message><ns4:error-type>CLIENT</ns4:error-type></ns4:error>`

**signatures.xml fil**
[signatures.xml.txt](https://github.com/digipost/signature-api-specification/files/4779830/signatures.xml.txt)

**Comment by simenstoa** [comment]
Hei, og beklager at det har tatt så lang tid før du får svar. Sliter du fortsatt med dette, eller fant du ut av det?

**Comment by eikybreaky** [comment]
Hei, og takk for svar. Eg fant ut av det sjølv til slutt. 

Det var som feilmeldinga sa eit problem med sertifikat informasjonen, feilen var at eg henta inn `subject` i feltet `X509IssuerName`, det skulle sjølvsagt vere `issuer` i det feltet.

Så det var bare ein flau feil frå mi side.
