### ISSUE TITLE
500 under hent pades

### ISSUE THREAD

**Issue by boguszjelinski** [digipost/signature-api-specification#174]
av og til får jeg 500 når jeg henter et pades dokument. Kan noen sjekke i loggen hva som var årsaken for eksempel i dette tilfellet i går:
2020-10-20T13:21:43,764Z 
http://api-signering-posten-no.app2ext.sikker-prod.skead.no/api/974761076/archive/documents/3472585--j/pades 
 500 Internal Server Error

**Comment by boguszjelinski** [comment]
errata: starten av URL-en er min proxy til PROD miljøet. Timestamp / orgnr / jobb id skal brukes ;)

**Comment by simenstoa** [comment]
Hei! Sjekket ut feilen, og det ser ut som det var nettverksrelatert. Ser også ut som det bare feilet en gang, har dere satt opp noen form for retry-mekanisme?

**Comment by boguszjelinski** [comment]
Vi har ikke noen retry-mekanisme, det var med tanken at token kan brukes
bare én gang og har kanskje begrenset levetid.
Kan token gjenbrukes etter at det første forsøket feiler med timeout *?*
I siste 40 dager har vi hatt 26 feil, så nesten hver dag feiler en
signering - se vedlegg.
Hilsen,
Bogusz

ons. 28. okt. 2020 kl. 10:40 skrev Simen Støa <notifications@github.com>:

**Comment by boguszjelinski** [comment]
nei, ikke hver dag som det feiler, "hver tredje dag" er nærmere sannheten.

ons. 28. okt. 2020 kl. 10:40 skrev Simen Støa <notifications@github.com>:

**Comment by simenstoa** [comment]
Url'en for å hente PAdES trenger ikke tokenet, og er brukbart i 40 dager. En `500`-feil fra oss betyr at dere skal kunne forsøke på nytt, men gjerne med en backoff.

**Comment by simenstoa** [comment]
Hei, er det noe mer jeg kan hjelpe deg med, eller er det greit at jeg lukker issuet?

**Comment by boguszjelinski** [comment]
lukk. jeg har laget "retry", og jeg har opplevd sånne tilfeller noen ganger
i TEST, dessverre "retry" har ikke hjulpet. Jeg kommer tilbake til deg om
noen få måneder med en ny oppsummering fra PROD.

tir. 10. nov. 2020 kl. 13:31 skrev Simen Støa <notifications@github.com>:
