### ISSUE TITLE
Problemer med signering i Chrome (401)

### ISSUE THREAD

**Issue by falvestad** [digipost/signature-api-specification#199]
Hei. 
Vi er i ferd med å teste en ny signeringsløsning for en kunde. 
Vi benytter direkteflyt, og har i det siste fått feilmelding ved ferdigstilling av signeringen. Feilen oppstår etter bankid-dialogen (engangskode og pssord er oppgitt), idet vi forventer redirect tilbake til vår tjeneste.
![image](https://user-images.githubusercontent.com/83351547/116409320-07597100-a834-11eb-9268-ed8483f2ba93.png)

Nettleseren viser videre denne feilen
![image](https://user-images.githubusercontent.com/83351547/116410233-daf22480-a834-11eb-851d-c9ac4120123b.png)

Signering fungerer fint i Edge og Firefox, men feilen oppstår konsekvent i Chrome for v90.0.4430.93 og  Versjon 90.0.4430.85 (bekreftede versjoner). Signering i Chrome har fungert tidligere.

Er dette en kjent problemstilling?

**Comment by falvestad** [comment]
Feilen oppstår også i testportalen [https://difitest.signering.posten.no](url) ved bruk av avansert e-signatur. Autentisert e-signatur fungerer fint.

**Comment by simenstoa** [comment]
Hei! Beklager sent svar, men dette skal være fikset nå. Beklager problemene det skapte.
