### ISSUE TITLE
Er maksverdier for expiration-time satt i dokumentasjonen?

### ISSUE THREAD

**Issue by aberner** [digipost/signature-api-specification#23]
ref. https://github.com/digipost/signature-api-specification/blob/master/schema/xsd/portal.xsd
Der står det:

"Please refer to the documentation to determine the default expiration-time, as well as the limit for how far in the future a job can be set to expire."

Hvor er dette dokumentert?

**Comment by runeflobakk** [comment]
Per nå har vi bare stukket fingern i været og satt default expiration-time til 30 dager (dersom man ikke spesifiserer noe), og begrenset hvor langt inn i fremtiden expiration-time kan settes til 90 dager. Disse verdiene er enkle å endre på. Rasjonalet er å forhindre at vi får signeringsjobber som "bare blir liggende".

Hvis dette høres greit ut så skal vi få det inn i dokumentasjonen også.

**Comment by aberner** [comment]
Jeg tenker at det kan tas i inn i dokumentasjonen uansett om det høres greit ut eller ikke. Så er det ihvertfall dokumentert hvordan systemet fungerer. 
jeg har selv ingen input på hva disse burde være satt til.
