### ISSUE TITLE
Direct flow - skal redirect Url peke på frontend eller backend i direct flow?

### ISSUE THREAD

**Issue by boguszjelinski** [digipost/signature-api-specification#231]
Hei, detter er ikke en issue, kun et viktig spørsmål, svaret er ikke entydig her på bildet, spør noen meg: https://signering-docs.readthedocs.io/en/latest/client-integration/direct-flow.html
Skal redirectUrl peke på path i Reacts Router eller på et endepunkt i backend? Det funker ikke så dårlig med Router men antall feil som er knyttet til den arkitekturen er altfor høyt, inkl. at backend får dupliserte "hent status" requester. Hvis jeg kunne unngå at Frontend kaller backend to ganger i flyten ville det redusere antall feil, tror jeg.
Hva er deres anbefaling? takk.

**Comment by simenstoa** [comment]
Hei! 

Direkteflyt skal fungere fint med redirect-url både til frontend og til backend. Det kommer mest an på hvordan applikasjonen deres fungerer, så vi kan derfor ikke gi noen entydig anbefaling på hva som er best.

Mvh Simen

**Comment by runeflobakk** [comment]
Det er vanskelig å gi noen anbefaling her, siden vi ikke kjenner til systemet deres. Hvis du kan gi noen flere detaljer som tar for seg litt mer konkret hvilken oppførsel med API-et til Posten signering du mener skaper utfordringer i deres applikasjon(er), og hvorfor, så kan det hende at vi kan bistå. Men vi kjenner ikke til hvordan deres frontend kommuniserer med deres backend, og kan derfor ikke si så mye om hvorfor du opplever flere requests til deres backend, ei heller vet vi hvorfor dette er problematisk.

Lukker denne saken, men det er bare å legge til mer informasjon om ønskelig, så kan vi se om vi forstår problemstillingen noe mer!
