### ISSUE TITLE
ASICE_VALIDATION_FAILED

### ISSUE THREAD

**Issue by thomastloberg** [digipost/signature-api-specification#289]
Hei. Holder på å oppgradere eksisterende php signerings implementering med nytt sertifikat fra Buypass.
Det nye virksomhetssertifikatet er G2 (SEID 2.0) mot det gamle sertifikatet som er SEID 1.0.

Steg jeg har prøvd:

1. Om jeg lar alle SSL instillingene stå som standard så får jeg:
`SSL certificate problem: unable to get local issuer certificate`
(dette var den samme utfordringen før bytte av sertifikat og ble unngått med å implementere steg 2 under)

2. Om jeg slår av `CURLOPT_SSL_VERIFYPEER` så får jeg:
`SSL: certificate subject name 'POSTEN NORGE AS' does not match target host name 'api.difitest.signering.posten.no'`

3. Om jeg slår av `CURLOPT_SSL_VERIFYHOST` så får jeg:
`ASICE_VALIDATION_FAILED`
`Error when valicating ASiCE: Verification of XAdES signature failed. [Error='Verification failed for property 'SigningCertificate': cannot verify reference for certificate 2.5.4.97=#0c0f4e54524e4f2d393538323834383337,CN=SIM IKS TEST,OU=zpirit,O=SUNNHORDLAND INTERKOMMUNALE MILJØVERK IKS,C=NO']`

4. Om jeg følger [Buypass sin dokumentasjon](https://buypassdev.atlassian.net/wiki/spaces/BCA/pages/2182479873/Endringer+i+Buypass+personsertifikater+og+virksomhetssertifikater) ang. oppgradering til SEID 2.0 så skal nå serialNumber fra sertifikat være byttet ut med ny OID / OrganisationIdentifier. Når jeg bruker oppdatert serialNumber så får jeg:
`ASICE_VALIDATION_FAILED`
`Error when valicating ASiCE: Parse error: Failed to parse XAdESSignatures`

Ekstra informasjon:

Virksomhetssertifikatet som kom i p12 fra Buypass er konvertert til PEM i løsningen.

Forrige sertikat (SEID 1.0):
Subject: C=NO, O=SUNNHORDLAND INTERKOMMUNALE MILJØVERK IKS, CN=SUNNHORDLAND INTERKOMMUNALE MILJØVERK IKS, serialNumber=958284837
Issuer: C=NO, O=Buypass AS-983163327, CN=Buypass Class 3 CA 3

Nytt sertifikat (SEID 2.0):
Subject: C=NO, O=SUNNHORDLAND INTERKOMMUNALE MILJØVERK IKS, OU=zpirit, CN=SIM IKS TEST, 2.5.4.97=NTRNO-958284837
Issuer: C=NO, 2.5.4.97=NTRNO-983163327, O=Buypass AS, CN=Buypass Class 3 Test4 CA G2 ST Business

Fra http request:
Endepunkt: https://api.difitest.signering.posten.no/api/958284837/direct/signature-jobs
[signatures.xml.txt](https://github.com/digipost/signature-api-specification/files/12701394/signatures.xml.txt)

**Comment by runeflobakk** [comment]
Litt generelt først:
Bytte til nytt klient-virksomhetssertifikat fra SEID 1 til SEID 2 skal kunne gjøres som en drop-in replacement, og API-et til Posten signering godtar virksomhetssertifikater på både SEID 1- og SEID 2-format. Litt avhengig av klienters sertifikathåndtering, må man også inkludere aktuelle CA-sertifikatkjeder i sertifikatbytte.

API-et til Posten signering bruker fremdeles SEID 1 virksomhetssertifikat som sitt server-sertifikat, og derfor må ikke validering av server-sertifikatet til Posten signering forvente et SEID 2-sertifikat.

For å ta punkt for punkt:

1. SSL-innstillinger kan ikke endres til å være "standard", da dette ikke er en standard TLS-tilkobling. Feilmeldingen `SSL certificate problem: unable to get local issuer certificate` tror jeg tyder på at TLS/SSL-stacken forventer et standard TLS-sertifikat, og derfor ikke godtar Posten sitt SEID 1 virksomhetssertifikat når TLS-tilkobling skal etableres.
2. `CURLOPT_SSL_VERIFYPEER` antar jeg er verifisering at sertifikatet til API-et har subject-navn som stemmer med hostname man kobler til. Dette må også være avskrudd av samme årsak som 1, dette er ikke en standard TLS-tilkobling, siden server identifiserer seg med et virksomhetssertifikat vil det ikke være utstedet for å brukes med et bestemt hostname. Det har "POSTEN NORGE AS" som subject name, som du ser i feilmeldingen. `CURLOPT_SSL_VERIFYPEER` må altså være skrudd av.


Så med pkt. 1 og 2 løst får du nå feil tilbake fra API-et når Posten signerer åpner og validerer dokumentpakken. Dette betyr at selve TLS-håndteringen og API-autentiseringen og -autoriseringen med sertifikater er riktig satt opp. 


Feilmeldingene du får i pkt. 4 tyder på feil når vi skal lese innholdet i [dokumentpakken](https://signering-docs.readthedocs.io/en/latest/egen-integrasjon/dokumentpakke.html), og dette er en ren XML-parsing feil som skjer når vi prøver å lese inn `META-INF/signatures.xml`, ikke noe som går på noe signatur-/kryptografi-relatert (og det er bra, for det er gjerne så innmari mye vanskeligere å løse...). 
Jeg forsøkte å parse `signature.xml.txt`, og får feilen:

```
lineNumber: 141; columnNumber: 79; cvc-datatype-valid.1.2.1:
'NTRNO-983163327' is not a valid value for 'integer'
```
Og her ser jeg følgende:
```xml
<IssuerSerial>
  <ns2:X509IssuerName>C=NO, 2.5.4.97=NTRNO-983163327, O=Buypass AS, CN=Buypass Class 3 Test4 CA G2 ST Business</ns2:X509IssuerName>
  <ns2:X509SerialNumber>NTRNO-983163327</ns2:X509SerialNumber>
</IssuerSerial>
```
Dette skal være en ren sertifikat-referanse, og her skal serialNumber til sertifikatet brukes i `ns2:X509SerialNumber`-elementet (det forventer en integer).


Dersom du går tilbake til å referere til sertifikatets serialNumber her, er du da tilbake til pkt. 3 ("Verification of XAdES signature failed.")?

**Comment by thomastloberg** [comment]
Virker nå! :D

Endret til sertifikat serialnumber (integer) og fant en feil i hvordan sertifikat-digest ble utreknet.
Oppdatert:
1. Hent første sertifikat segment.
2. Decode base64
3. SHA1 encrypt og binær output med: openssl_digest($cert, 'sha1', true)
4. Encoder tilbake til base64 
5. Oppdater signatures.xml:
<ns2:DigestValue>%her%</ns2:DigestValue>

Da gikk signeringen igjennom. Har også lagt til kommentarer slik at SSL -ingrepene ikke blir endret på.


Når jeg signerer dokumentet hos Posten og skal bli redirektet til completion-url så får jeg opp
'Noe gikk galt
En feil oppstod under signeringen. Hvis du ønsker, kan du prøve igjen.'
i stedet. Er dette fordi den skal sende meg tilbake til localhost eller kan det være en annen årsak? :o

[metadata.xml.txt](https://github.com/digipost/signature-api-specification/files/12714239/metadata.xml.txt)

**Comment by thomastloberg** [comment]
Her er det feil på mitt endepunkt når bruker kommer tilbake til tjenesten. Takk for assistansen! :)

**Comment by thomastloberg** [comment]
Ser jeg var litt snar med å lukke saken før jeg fikk testet hele prosessen.
Når jeg signerer dokumentet digitalt i testmiljø og skal i utgangspunktet bli sendt tilbake til tjenesten min så opplever jeg å få:
"Noe gikk galt
En feil oppstod under signeringen. Hvis du ønsker, kan du prøve igjen."

Om jeg avviser istedet for å signere så blir jeg sendt tilbake til rejection-url slik jeg skal.

Får du noen feilkode?

Endepunktet jeg blir sendt til etter signert med bankid er:
https://preprod.signicat.signering.posten.no/std/docaction/difi/responsive/abs/?performedAction=authbased&methodName=idporten-abs-niva4-nossn-sign

Endepunktene er lik de som var før og i følge direct-flow flytskjema så skal det ikke være noe handshake e.l. etter bruker har bekreftet signatur med bankid?

Kopi av metadata.xml:
[metadata.xml.txt](https://github.com/digipost/signature-api-specification/files/12731794/metadata.xml.txt)

**Comment by runeflobakk** [comment]
Bruker du en "[syntetisk test-ID](https://www.skatteetaten.no/skjema/testdata/)" til å signere med? Altså klikker du TestID i bildet under?
<img width="568" alt="velg-eID" src="https://github.com/digipost/signature-api-specification/assets/174823/1f72e811-81c1-4ce4-af1f-b69b9851fdf0">
Det er p.t. dessverre kun TestID som støttes for autentisert signatur i testmiljøer.

Dersom du bruker en BankID-testbruker må du velge avansert signatur.

Så lenge integrasjonsflyt fungerer for _enten_ avansert eller autentisert signatur, kan du anta at det vil fungere i produksjon for begge i produksjon.

**Comment by thomastloberg** [comment]
Virket supert med syntetisk data via TestID. Takk! :)

**Comment by runeflobakk** [comment]
Good good! 😁
