### ISSUE TITLE
Skal du bruke databehandler eller behandlingsansvarlig sitt org.nummer i rot-url?

### ISSUE THREAD

**Issue by aberner** [digipost/signature-api-specification#29]
I README.md kapitel: "Om rot-URL" står det følgende:

"Du må også vite din avsenderidentifikator. Pr. i dag er dette din organisasjons org.nummer."

- Hvordan fungerer dette om jeg er en databehandler på vegne av fler behandlingsansvarlige?
- Hvordan fungerer dette om jeg er både behandlingsansvarlig og databehandler?

Jeg tror det bør spesifiseres om dette er din databehandler sitt org.nummer eller om det er org.nummer til den enkelte behandlingsansvarlige.

**Comment by lillesand** [comment]
Fikset i 03e5d3f450c4a6f50591a53f802a864078020942.
