### ISSUE TITLE
Pades-URL endringer

### ISSUE THREAD

**Issue by adoermenen** [digipost/signature-api-specification#290]
Hei dere.

Opplever en litt merkelig sak relatert til Pades-URL'ene vi får tilbake når vi henter status på signerings-jobber. 

Det er litt tilfeldig om vi ved første status-request etter fullført signering får en URL som følger formatet
https://api.signering.posten.no/api/org-nummer/archive/documents/job Id--j/pades
eller
https://api.signering.posten.no/api/org-nummer/archive/documents/32-tegns GUID/pades

Hvis man kjører en ny status-oppdatering på jobber med Job-id i URL'en så endres de til en GUID-basert URL etter noe tid. 

I tillegg så virker det som at det eksisterer en redirect fra gammel job-id URL til ny GUID URL og denne skaper litt trøbbel for oss da plattformen vår integrasjon kjører i ikke ser ut til å håndtere redirecten på en god måte. 

Rimelig sikker på at redirect-problemet ligger på vår ende men for å komme fram til en god løsning så hadde det vært hjelpsomt med litt informasjon fra dere:

1. Er det slik at Pades-URL'en endres på et eller annet punkt etter signering og hvordan er i så fall timingen på dette?

2. Flyt-diagrammet for direkte-signering (https://raw.githubusercontent.com/digipost/signature-api-specification/main/integrasjon/flytskjemaer/synkron-maskin-til-maskin.png) spesifiserer at man skal "bekrefte ferdig prosessering" før dokumentene lastes ned mens teksten spesifiserer det motsatte (Step 4 - Get Signed Documents. Step 5 - Confirm finished processing). Hva er riktig rekkefølge?

**Comment by runeflobakk** [comment]
1. Pades-URL endres på et punkt, _etter_ at et oppdrag er ferdigsignert, slik du opplever. Da vil "gammel" URL gi tilbake en standard `301 Moved Permanently`-respons med den nye URL-en med UUID/GUID. Redirects er et standard aspect i HTTP, og burde være mulig å skru på i HTTP-klienten man bruker, om det ikke er skrudd på by default. 

Timingen vil være noe ulik fra gang til gang, og er egentlig ikke noe man lene seg på. 
Det du ev. _kan_ gjøre, dersom du ikke får skrudd på "follow redirect" i klienten du bruker, er å inspisere URL-en du får etter at jobben er ferdigsignert, og forkaste statusoppdateringen inntil du får en URL som _ikke_ inneholder `<jobId>--j`, og kan da anta at dette er "final" URL. Dette er _egentlig_ ikke å anbefale, da API-et i prinsippet på et senere tidspunkt kan gi en ny redirect-respons, og da vil ~hacken~ workarounden ikke fungere lenger. Dog er nok dette svært lite sannsynlig at det vil dukke opp mer redirects her.

2. "bekrefte ferdig prosessering" betyr egentlig at status-responsen er mottatt, og trenger ikke å bli utlevert lenger fra API-et. Ideelt sett bør prosessering av en statusrespons være så rask og enkel som mulig, typisk bare å persistere den, slik at man på et senere tidspunkt kan gjøre handlinger knyttet til håndteringen av status på jobben, f.eks. laste ned ferdigsignert dokument (PAdES). Men det er ikke noe i veien for å gjøre nedlasting av PAdES samtidig som man får en status-respons og prosesserer responsen, det blir litt opp til hver enkelt integrasjon. I øyeblikket man "bekrefter ferdig prosessering" så signaliserer du til API-et at denne status-oppdateringen ikke skal bli utlevert lenger. Dersom man _ikke_ "bekrefter ferdig prosessering" vil statusoppdateringen bli utlevert på nytt. Dette er for å forhindre at man "mister" en statusoppdatering i tilfelle man har en feil (exception) i håndteringen.

**Comment by runeflobakk** [comment]
Lukker denne. Åpne den igjen om du har behov for det.
