### ISSUE TITLE
Migreringguide fra signature-api-client-java 6.x til 7.x

### ISSUE THREAD

**Issue by kajh** [digipost/signature-api-specification#299]
Det kunne vært nyttig om dere hadde en migreringguide fra signature-api-client-java 6.x til 7.x.

Vi bruker i dag signature-api-client-java versjon 6.1.1 i tjenesten Nettskjema og har begynt på å se på å oppgradere til 7.0.1 fordi vi skal oppgradere til Spring boot 3 og trenger bla jakarta støtten i signature-api-client-java 7.x.

Bla klassene Certificates og ServiceUri ikke lenger ser ut til å finnes lenger.

Eksempel på kode vi har i dag:
```
   private DirectClient createClient(final ServiceUri serviceUri, final Certificates certificates) {
       Builder builder = ClientConfiguration.builder(
               new KeyStoreConfig(
                       SecurityUtils.getKeystore(keystorePassword, keystorePath), KEYSTORE_ALIAS,
                       keystorePassword, keyEntryPassword))
               .globalSender(UIO)
               .serviceUri(serviceUri)
               .trustStore(certificates);
       return new DirectClient(builder.build());
   }
```

Vi er klar over dokumentasjonen dere har på https://signering-docs.readthedocs.io/en/latest/, men for noen av oss som ikke kjenner signeringstjenesten så godt hadde migreringguide vært nyttig.

**Comment by kajh** [comment]
Kan det være at dokumentasjonen på https://signering-docs.readthedocs.io/en/latest/client-integration/create-client-configuration.html ikke er oppdatert for versjon 7.x?

Der står det
```
ClientConfiguration clientConfiguration = ClientConfiguration.builder(keyStoreConfig)
        .trustStore(Certificates.TEST)
        .serviceUri(ServiceUri.DIFI_TEST)
        .globalSender(new Sender("123456789"))
        .build();
 ```
Det kan se ut som `Builder` som returneres fra `ClientConfiguration.builder(keyStoreConfig)` ikke har metoden `.trustStore`.

**Comment by runeflobakk** [comment]
v7 ble sluppet i final versjon for et par uker siden, og vi har ikke hatt tid til å dokumentere hva som er nytt. Det meste som er nytt er egentlig bare "under panseret" med et bytte fra Jersey Client til Apache Http Client v5, og kompatibilitet med jakarta (og Spring Boot 3, som du også nevner). Vi benytter selv biblioteket med Spring Boot 3 i en av våre applikasjoner.

`DirectClient`, som du benytter, er uendret foruten at metodene som tidligere returnerte `InputStream` (typisk nedlasting av signert dokument) nå returnerer en mer spesifikk `ResponseInputStream`, men denne er kompatibel med eksisterende kode som bruker metodene.

Endringer i API-et til biblioteket er først og fremst i bygging av konfigurasjon.
`ServiceUri` og sertifikater for `.trustStore(..)` er samlet i `ServiceEnvironment`, og kan settes slik:
```diff
< .serviceUri(serviceUri)
< .trustStore(certificates)
> .serviceEnvironment(ServiceEnvironment.PRODUCTION) // resolve ev. miljø basert på egen konfigurasjon
```

"global sender" er byttet til å hete "default sender":
```diff
< .globalSender(UIO)
> .defaultSender(UIO)
```

`KeyStoreConfig` skal være som før

**Comment by kajh** [comment]
Tusen takk for grundig svar!

Vi kjører foreløpig på Spring boot 2.7.16 og Java 20.

Jeg har noen spørsmål nedenfor:

1. Hvilket `ServiceEnvironment` skal vi bruke i våre utviklings- og staging miljøet? `ServiceEnvironment.DIFITEST`?

2. Jeg fikk `java.lang.NoClassDefFoundError: org/apache/hc/client5/http/config/ConnectionConfig` ved oppstart etter oppgradering av `signature-api-client-java` fra 6.1.1 til 7.0.1, så jeg la til
```
<dependency>
    <groupId>org.apache.httpcomponents.client5</groupId>
    <artifactId>httpclient5</artifactId>
    <version>5.1.2</version>
</dependency>
```
...og da får jeg følgende under oppstart:
```
Failed to instantiate [no.digipost.signature.client.direct.DirectClient]: Factory method 'testingDirectClient' threw exception; nested exception is java.lang.NoSuchMethodError: 'org.apache.hc.core5.util.Timeout org.apache.hc.core5.util.Timeout.of(java.time.Duration)'","logger_name":"org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext"
```
Noen tips? :)

**Comment by kajh** [comment]
Angående `NoSuchMethodError` feilmeldingen ser jeg at vi får med httpclient v4 via software.amazon.awssdk:s3 versjon 2.20.155. Bare fyi i tilfelle det er relevant. Se output fra `mvn dependency:tree` nedenfor:

```
[INFO] +- software.amazon.awssdk:s3:jar:2.20.155:compile
[INFO] |  +- software.amazon.awssdk:aws-xml-protocol:jar:2.20.155:compile
[INFO] |  |  \- software.amazon.awssdk:aws-query-protocol:jar:2.20.155:compile
[INFO] |  +- software.amazon.awssdk:protocol-core:jar:2.20.155:compile
[INFO] |  +- software.amazon.awssdk:arns:jar:2.20.155:compile
[INFO] |  +- software.amazon.awssdk:profiles:jar:2.20.155:compile
[INFO] |  +- software.amazon.awssdk:crt-core:jar:2.20.155:compile
[INFO] |  +- software.amazon.awssdk:sdk-core:jar:2.20.155:compile
[INFO] |  |  \- org.reactivestreams:reactive-streams:jar:1.0.4:compile
[INFO] |  +- software.amazon.awssdk:auth:jar:2.20.155:compile
[INFO] |  |  \- software.amazon.eventstream:eventstream:jar:1.0.1:compile
[INFO] |  +- software.amazon.awssdk:http-client-spi:jar:2.20.155:compile
[INFO] |  +- software.amazon.awssdk:regions:jar:2.20.155:compile
[INFO] |  +- software.amazon.awssdk:annotations:jar:2.20.155:compile
[INFO] |  +- software.amazon.awssdk:utils:jar:2.20.155:compile
[INFO] |  +- software.amazon.awssdk:aws-core:jar:2.20.155:compile
[INFO] |  +- software.amazon.awssdk:metrics-spi:jar:2.20.155:compile
[INFO] |  +- software.amazon.awssdk:json-utils:jar:2.20.155:compile
[INFO] |  |  \- software.amazon.awssdk:third-party-jackson-core:jar:2.20.155:compile
[INFO] |  +- software.amazon.awssdk:endpoints-spi:jar:2.20.155:compile
[INFO] |  +- software.amazon.awssdk:apache-client:jar:2.20.155:runtime
[INFO] |  |  +- org.apache.httpcomponents:httpclient:jar:4.5.14:runtime
[INFO] |  |  \- org.apache.httpcomponents:httpcore:jar:4.4.16:runtime
```

**Comment by runeflobakk** [comment]
Apache HTTP Client v4 og v5 skal fint kunne sameksistere, da de bruker ulike avhengighetskoordinater (groupId/artifactId) og ulik intern pakkestruktur. Kan anse de som separate biblioteker, så ev. bruk av v4 fra før i samme applikasjon skal ikke interferere med v5 som brukes av klientbiblioteket.

signature-api-client-java avhenger av https://github.com/digipost/signature-api-client-java/blob/main/lib/pom.xml#L67-L76 (eller nyere), og vil dra med disse selv via vanlig (transitiv) dependency resolution med Maven/Gradle, med mindre du selv eksplsitt overstyrer versjon i din egen applikasjon med f.eks. `<dependencyManagement>`.

`Timeout`-klassen ligger i httpcore5, og metoden den mangler `Timeout of(Duration)` ble lagt til i [httpcore5 versjon 5.2](https://javadoc.io/static/org.apache.httpcomponents.core5/httpcore5/5.2.3/org/apache/hc/core5/util/Timeout.html#of-java.time.Duration-). Har du denne blant avhengighetene dine?

**Comment by runeflobakk** [comment]
Du kan gjerne bruke `ServiceEnvironment.STAGING`, da det er et alias for hva som er å anse som et public staging/test-miljø
https://github.com/digipost/signature-api-client-java/blob/main/lib/src/main/java/no/digipost/signature/client/ServiceEnvironment.java#L21-L30

Det peker p.t. til `ServiceEnvironment.DIFITEST`.

**Comment by kajh** [comment]
> Timeout-klassen ligger i httpcore5, og metoden den mangler Timeout of(Duration) ble lagt til i [httpcore5 versjon 5.2](https://javadoc.io/static/org.apache.httpcomponents.core5/httpcore5/5.2.3/org/apache/hc/core5/util/Timeout.html#of-java.time.Duration-). Har du denne blant avhengighetene dine?

Ahhh tusen takk! Da la jeg den til denne og da fikk jeg startet appen :) 

Nå gjenstår det bare å få åpnet for api.difitest.signering.posten.no i brannmuren vår, så kan vi få testet dette :) Skal melde tilbake her når vi har fått testet.

**Comment by runeflobakk** [comment]
Jeg er litt nysgjerrig på hvorfor du trenger å eksplisitt deklarere avhengigheter til httpclient5 og httpcore5? Den eneste grunnen jeg kan komme er dersom du også har noe annet i avhengighetsgrafen din som _også_ avhenger av Apache Http Client v5 men en tidligere minor-versjon, og du derfor må "styre" versjonen til hhv 5.2.1 og 5.2.2.

I vår Spring Boot 3-applikasjon deklarerer vi kun avhengighet til `signature-api-client-java` og får med riktige versjoner av Apache Http Client sammen med den. Vi er for øvrig også på Spring Boot 3.1, som selv [styrer versjon til 5.2.1 og 5.2.2](https://github.com/spring-projects/spring-boot/blob/v3.1.4/spring-boot-project/spring-boot-dependencies/build.gradle#L435). Men ser at Spring Boot 3.0 var på [v5.1 av Apache Http Client](https://github.com/spring-projects/spring-boot/blob/v3.0.11/spring-boot-project/spring-boot-dependencies/build.gradle#L413), så det kan hende versjonen kommer derfra?

Anbefaler følgende deklarasjon for å få riktige versjoner:
```xml
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>no.digipost.signature</groupId>
                <artifactId>signature-api-client-bom</artifactId>
                <version>7.0.1</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.apache.httpcomponents.core5</groupId>
                <artifactId>httpcore5</artifactId>
                <version>5.2.2</version>
            </dependency>
            <dependency>
                <groupId>org.apache.httpcomponents.client5</groupId>
                <artifactId>httpclient5</artifactId>
                <version>5.2.1</version>
            </dependency>
...
```
(ideelt skulle du kunne utelate å deklarere httpclient5 og httpcore5, men dersom Spring Boot eller noe annet styrer dette til 5.1 eller tidligere versjon, så må du nesten tvinge versjonen opp til 5.2)


Og deklarer direkte avhengighet til klientbiblioteket (uten versjon, da det kommer via `signature-api-client-bom`)
```xml
    <dependencies>
        <dependency>
            <groupId>no.digipost.signature</groupId>
            <artifactId>signature-api-client-java</artifactId>
        </dependency>
...
```

**Comment by kajh** [comment]
Jeg ble nysgjerrig på det samme selv :) og det er på grunn av denne:
```
INFO] +- org.sourcelab:java-hkp-client:jar:0.2.0:compile
[INFO] |  +- org.apache.httpcomponents.client5:httpclient5:jar:5.1.4:compile
[INFO] |  |  +- org.apache.httpcomponents.core5:httpcore5:jar:5.1.5:compile
[INFO] |  |  \- org.apache.httpcomponents.core5:httpcore5-h2:jar:5.1.5:compile
```

Vi har litt brannmurproblemer: 
```
Error signing submission for form "TSD p11 - Signering" (id: 900634), with cause org.apache.hc.client5.http.ConnectTimeoutException: Connect to https://api.difitest.signering.posten.no:443 [api.difitest.signering.posten.no/51.105.206.85] failed: Connect timed out
```

Jeg er usikker på om det kan være relatert til at api.difitest.signering.posten.no ikke har et gyldig sertifikat:
```
$ curl https://api.difitest.signering.posten.no/
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```
Vil dere vurdere å fikse sertifikat til denne hosten?

**Comment by kajh** [comment]
Følgende kode kjørt samme sted som jeg fikk feilmelding om signering ovenfor sier at porten er åpen:
```
        try (Socket socket = new Socket()) {
            SocketAddress addr = new InetSocketAddress("software-proxy.uio.no", 3128);
            Proxy proxy = new Proxy(Proxy.Type.HTTP, addr);
            URL url = new URL("https://api.difitest.signering.posten.no/");
            url.openConnection(proxy);

            logger.info("Port is open");
        } catch (Exception e) {
            logger.info("Port is closed: " + e.getMessage());
        }
 ```

**Comment by kajh** [comment]
Aha ja, dette er selvsagt samme url som vi bruker fra før for test med versjon 6. Det tenkte jeg ikke på. Da skal vi se nærmere på dette etter høstferien. Takk for hjelpen og gode forklaringer!

**Comment by runeflobakk** [comment]
Bare hyggelig, håper det ordner seg over ferien! Ellers får du bare fyre løs!

**Comment by runeflobakk** [comment]
Har oppdatert dokumentasjon for [ClientConfiguration](https://signering-docs.readthedocs.io/en/latest/client-integration/create-client-configuration.html) til v7, samt notert litt ang. [hva som er nytt i v7](https://github.com/digipost/signature-api-client-java/releases/tag/7.0.1).

Lukker denne nå, men du får bare åpne den igjen hvis du trenger noe mer hjelp!

**Comment by erlendfg** [comment]
Jeg har skrudd på wire-logging i HttpClient og ser ingen feil. Derfor mistenker jeg at default socket timeout er for lav siden den er satt til 5 sekunder. Jeg tittet litt i `ClientConfiguration`, men socketTimeout og de beslektede innstillingene var ikke så lett å få tilgang til.

**Comment by kajh** [comment]
@runeflobakk Vi fant ut av dette.

**Comment by runeflobakk** [comment]
Bare for reference, socket- og andre timeouts kan settes via [.timeout(..) og .timeoutForDocumentDownloads(..)](https://javadoc.io/static/no.digipost.signature/signature-api-client-java/7.0.1/no/digipost/signature/client/ClientConfiguration.Builder.html#timeouts(java.util.function.Consumer)).

F.eks. slik:
```java
ClientConfiguration.builder(keystoreConfig)
        .timeouts((TimeoutsConfigurer t) -> t //kan utelate "TimeoutsConfigurer", inkludert for tydelighet
                .socketTimeout(Duration.ofSeconds(10))
                .connectTimeout(Duration.ofSeconds(6))
                .connectionRequestTimeout(Duration.ofSeconds(20)))
        .timeoutsForDocumentDownloads(t -> t.socketTimeout(Duration.ofSeconds(10)))
        ...
```
Her er litt diverse timeouts satt for "vanlig API-kommunikasjon", og en egen socket timeout satt spesifikt for nedlasting av dokumenter.

Socket timeout går på monitorering av datastrømmen, og at det tillates "stopper" i datastrømmen før klienten antar at her er connection ødelagt. 5 sekunder er egentlig i overkant raus verdi her, fordi det går på tillatt lengde på hver enkelt "stopp" i  datastrømmen, og datamengdene mellom hver sånn "chunk" kan være ganske liten.

**Comment by kajh** [comment]
Takk for gode forklaringer! Vi sliter fremdeles med at vi ikke får kontakt med signeringstjenesten med v7, se vedlagte skjermskudd.

Vi har samme proxyoppsett som vi har for v6 av biblioteket deres, og der funker det fint. Vi setter `https.proxyHost` og `https.proxyPort` med `System.setProperty`.

Kan det være noe i v7 som oppfører seg anderledes enn v6 med tanke på proxy?

![image](https://github.com/digipost/signature-api-specification/assets/2808619/789c558c-7126-40a7-9b55-2f5e67e49f3e)

**Comment by kajh** [comment]
Ahh kult! Vi skal teste dette og melde tilbake! Tusen takk!

**Comment by kajh** [comment]
> Ahh kult! Vi skal teste dette og melde tilbake! Tusen takk!

Funka! Tusen takk!

Bare en liten tilbakemelding på et variabelnavn, se følgende fra `ClientConfiguration`:
```
        public Builder httpProxyHost(String hostname, int port) {
            return this.proxyHost(URI.create(hostname + ":" + port));
        }
```
Her kan man lett bli forledet til å tro at `hostname` er et hostnavn og ikke en url, men det er det jo :)

**Comment by kajh** [comment]
Hei igjen :) Vi ser dere skriver følgende på https://github.com/digipost/signature-api-client-java/releases/tag/7.0.1
> Posten signering uses already uses this library with Spring Boot v3, with no additional tweaking besides depending on the library.

Vi holder på å oppgradere til Spring Boot 3.1.4 og nå sliter vi med at vi får `java.lang.ClassNotFoundException: com.sun.xml.bind.v2.JAXBContextFactory` under oppstart av appen i forbindelse med instansiering av `no.digipost.signature.client.direct.DirectClient`.

Vi bruker signature-api-client-java 7.0.2. 

Si gjerne fra hvis dere har noen tips.
.

**Comment by runeflobakk** [comment]
Når man deklarerer avhengighet til biblioteket på anbefalt måte v.h.a. `signature-api-client-bom` skal man få dette avhengighetstreet:
<img width="324" alt="client-dependency-tree" src="https://github.com/digipost/signature-api-specification/assets/174823/5cbb54db-cfea-4939-bab7-074a20c06f9e">
`com.sun.xml.bind.v2.JAXBContextFactory` ligger i `jaxb-impl:2.3.2`. Har dere noe som overstyrer denne avhengigheten?

**Comment by kajh** [comment]
Hos oss ser dette slik ut:
```
[INFO] +- no.digipost.signature:signature-api-client-java:jar:7.0.2:compile
[INFO] |  +- no.digipost.signature:signature-api-specification:jar:3.0.0:runtime
[INFO] |  \- no.digipost.signature:signature-api-specification-jaxb:jar:3.0.0:compile
[INFO] |     +- javax.xml.bind:jaxb-api:jar:2.3.1:compile
[INFO] |     |  \- javax.activation:javax.activation-api:jar:1.2.0:compile
[INFO] |     +- no.digipost:jaxb-resolver-com.sun.xml.bind:jar:1.0:runtime
[INFO] |     |  +- com.sun.xml.bind:jaxb-impl:jar:4.0.3:runtime
[INFO] |     |  \- com.sun.xml.bind:jaxb-core:jar:4.0.3:runtime
[INFO] |     \- org.jvnet.jaxb:jaxb2-basics-runtime:jar:2.0.9:compile
```
Er det rart at vi har `jaxb-impl:4.0.3` istedenfor `jaxb-impl:2.3.2`?

**Comment by runeflobakk** [comment]
`jaxb-impl` må være 2.3.2 (ikke senere), så det er nok noe annet i avhengighetsgrafen som overstyrer til den versjonen.

Jeg gjetter på at versjonen styres til 4.0.3 av [jaxb-bom](https://search.maven.org/remotecontent?filepath=org/glassfish/jaxb/jaxb-bom/4.0.3/jaxb-bom-4.0.3.pom) som dras inn av Spring Boot. I vår applikasjon har vi deklarert `signature-api-client-bom` _før_ `spring-boot-dependencies` i dependencyManagement, og det kan se ut som at det gjør at signature-api-client-bom får presedens. Prøv å flytte `signature-api-client-bom` tidlig under dependencyManagement.

Hvis dere bruker [spring-boot-starter-parent](org.springframework.boot:spring-boot-starter-parent:3.1.4) (vi gjøre ikke det), så vet jeg ikke hva som får presedens, men kan nok kanskje tyde på at versjoner via parent-pom får det. Da må du ev. selv manuelt styre jaxb-impl til versjon `2.3.2`. Kopier f.eks. disse linjene til egen dependencyManagement for å få riktige versjoner: https://github.com/digipost/jaxb-resolver-com.sun.xml.bind/blob/main/bom/pom.xml#L39-L54 

Dette skal ikke gå på bekostning av ev. nyere Jakarta EE 9 som benyttes i Spring Boot 3, fordi der benyttes Glassfish jaxb-runtime som JAXB-implementasjon. Det er egentlig litt rart at Glassfish sin jaxb-bom styrer "com.sun" sin jaxb-impl til 4.0.3.

**Comment by kajh** [comment]
Vi bruker `spring-boot-starter-parent`. Jeg la inn avhengighetene fra https://github.com/digipost/jaxb-resolver-com.sun.xml.bind/blob/main/bom/pom.xml#L39-L54 og da funker det som bare det! :) Tusen takk!
