### ISSUE TITLE
Alle har flere virksomhetssertifikater

### ISSUE THREAD

**Issue by aberner** [digipost/signature-api-specification#30]
Endre teksten:

"Dersom du har flere sertifikater så skal du benytte sertifikatet som har spesifisert KeyUsage DigitalSignature og ExtendedKeyUsage clientAuth."

til:

"Du skal benytte virksomhetssertifikatet som har spesifisert KeyUsage = DigitalSignature og ExtendedKeyUsage = clientAuth."

Dette fordi alle får utdelt 2 (buypass) eller 3 (commfides) virksomhetssertifikater fra sertifikatleverandørene når de kjøper et sertifikat.

**Comment by lillesand** [comment]
Fikset i #df03bf7

**Comment by lillesand** [comment]
Fikset i df03bf7
