### ISSUE TITLE
Manglende dokumentasjon av spesifikk protokoller, ciphers og TLS renegotiations

### ISSUE THREAD

**Issue by aberner** [digipost/signature-api-specification#31]
Hvilke protokoller og chipers kreves for å sette opp TLS forbindelse med signeringstjenesten?
Hvordan håndteres TLS renegotiations?

Er dette dokumentert, eventuelt hvor?

**Comment by lillesand** [comment]
Det er ikke vanlig å dokumentere de standard delene av et TLS-oppsett (hvertfall ikke ved bruk av HTTPs), og all denne informasjonen er tilgjengelig i handshaket og i en tjeneste som ssllabs.com.

TLS er en kritisk komponent for sikkerheten i tjenesten og det er et argument for å dokumentere mye om hvordan det virker. Samtidig er TLS kritisk for sikkerheten for nesten all webløsninger på Internett, og vi har et standard oppsett.

Det eneste vi gjør som kanskje er uvanlig er at vi bare støtter TLS 1.2 (og ikke 1.0 og 1.1). Er det tilstrekkelig for behovet ditt, eller ønsker du at vi dokumenterer mer?

**Comment by aberner** [comment]
Jeg oppfatter fra ssllabs rapporten at tjenesten ikke har noen spesielle krav til Cipher Suites, da er det heller ikke nødvendig å dokumentere dette.
Men det at bare TLS 1.2 støttes bør dokumenteres.

**Comment by lillesand** [comment]
Løst i 52d1fec2bdd831a36e55dc205a2e68e756afa23e
