### ISSUE TITLE
mangler flytdiagram som gir en oversikt over signeringsprosessen

### ISSUE THREAD

**Issue by aberner** [digipost/signature-api-specification#32]
Dokumentasjonen er ikke så leselig når det ikke er foreligger noen flytdiagram eller lignende som gir en innledende og overordnet oversikt over prosessen for signering. Dette vil kunne gjøre foreståelsen mye bedre for virksomheter som skal integrere mot løsningen.

**Comment by Espenhh** [comment]
@aberner da er flytskjema på plass. Basert på skjemaene som fantes i løsningsbeskrivelsen, men med noen steg-referanser for å koble de bedre opp mot den tekstlige beskrivelsen i dokumentasjonen. Kan sees her:
https://github.com/digipost/signature-api-specification
