### ISSUE TITLE
Hva skjer/betyr det dersom jeg kaller confirmation-url på et multisignatar oppdrag som ikke er fullført?

### ISSUE THREAD

**Issue by aberner** [digipost/signature-api-specification#34]
Scenario:
- jeg oppretter et multisignatar oppdrag med 3 signatarer
- en signatar har signert

Hva skjer dersom jeg sender følgende request:

POST https://api.difiqa.signering.posten.no/api/998877665/portal/signature-jobs/123/complete

Har det noe funksjon overhode?

Dersom jeg er fornøyd når 2 av 3 har signert, må jeg da alltid bruke:

https://api.difiqa.signering.posten.no/api/998877665/portal/signature-jobs/123/cancel

**Comment by runeflobakk** [comment]
Hei,

**POST til confirmation-url**

Som det er beskrevet i XSDen ([portal.xsd linje 91](https://github.com/digipost/signature-api-specification/blob/master/schema/xsd/portal.xsd#L91)), så er dette en bekreftelse av mottatt og håndtert status-oppdatering for en jobb. Den faktiske URLen er litt misvisende, ettersom den sier "complete", men dette er uansett ikke noe som klienten skal ha noe direkte forhold til, den skal kun vite at det er en URL som skal POSTes til når en status-oppdatering er håndtert. Dersom det ikke gjøres en POST til denne URLen så kan samme status-oppdatering komme igjen etter en viss tid. (Etter 10 minutter per dags dato)

Dette tilsvarer kommunikasjonen i SDP hvor avsender "puller" etter applikasjonskvitteringer hos Meldingsformidler, og må bekrefte mottak av disse.

Ressursen `/complete` i URLen henger igjen fra før vi støttet multisignatar-jobber. Vi har ikke prioritert å endre den faktiske URLen enda, da klient ikke trenger å ha noe forhold til "semantikken" i _pathen_ i URLen. Denne URLen må _alltid_ hentes fra statusoppdateringen.


**Når 2 av 3 signeringer er tilstrekkelig**

Dersom du er fornøyd når 2 av 3 har signert _kan_ du velge å bruke [cancellation-url](https://github.com/digipost/signature-api-specification/blob/master/schema/xsd/portal.xsd#L81) (dette er den samme URLen som også legges ved i hver statusoppdatering) for å avbryte oppdraget så siste signatar ikke får mulighet til å signere. En annen mulighet er å laste ned signerte dokument-artifakter når man har tilstrekkelig antall signaturer, tillate at jobben fortsatt er aktiv og la resterende signatarer signere, også velger avsender selv hva man ønsker å gjøre ved statusoppdateringer om nye signaturer. Man må altså da fremdeles POSTe til confirmation-url for mottatt statusendring, selv om man ev. ikke velger å agere noe på de. En tredje mulighet er å la jobben ligge til den løper ut på tid.
