### ISSUE TITLE
Hvilke felt kan jeg som avsender fylle med sensitive personopplysninger?

### ISSUE THREAD

**Issue by aberner** [digipost/signature-api-specification#35]
jeg kan ikke finne noe dokumentasjon på om metadata knyttet til et signeringsoppdrag kan inneholde sensitive personopplysninger eller ikke.
Er det noen av feltene som brukes i andre kanaler slik som f.eks. e-post/sms og som dermed ikke kan inneholde sensitive personopplysninger?

**Comment by lillesand** [comment]
https://github.com/digipost/signature-api-specification/pull/37

**Comment by aberner** [comment]
Dokumentasjonen er ok i forhold til hvordan løsningen nå er realisert men må endres i forbindelse med at bruk av tittel rettes opp i.

**Comment by Espenhh** [comment]
Dette er løst vha https://github.com/digipost/signature-api-specification/pull/37
