### ISSUE TITLE
Commitmeldinger bør være på norsk

### ISSUE THREAD

**Issue by lillesand** [digipost/signature-api-specification#36]
Både dokumentasjonen og issuene er på norsk. Det føles ganske keitete å skrive commitmeldingene på engelsk. 

Norsk fra nå av?

@Espenhh @runeflobakk @SindreNordbo @guroseter

**Comment by runeflobakk** [comment]
greit for meg

**Comment by Espenhh** [comment]
:+1:

**Comment by SindreNordbo** [comment]
Fant ingen emoji med norsk flagg, så da blir det et lite spektakulært: «greit for meg» fra meg også :)

**Comment by Espenhh** [comment]
Okei, da sier vi det sånn: norsk it is 🇳🇴🇳🇴🇳🇴🇳🇴🇳🇴

(og da har vi 0 åpne issues før helga :tada:
