### ISSUE TITLE
manglende releasenotes

### ISSUE THREAD

**Issue by aberner** [digipost/signature-api-specification#43]
Hvilke endringer er gjort fra release til release?
Det skal/bør følge med releasenotes for alle releaser gjort slik at det er mulig å enkelt få en oversikt over de endringer som er gjort.

**Comment by lillesand** [comment]
Enig i det! Vi har planlagt å skrive release notes før endringen går i produksjon, men du ønsker kanskje å få release notes allerede til testingen..?

**Comment by aberner** [comment]
Releasenotes kan med fordel være på plass når ny funksjonalitet er klar for testing. Virksomhetene/leverandørene som bruker løsningen bør kunne få info om hva som kommer av endringer i API'et før det er satt i produksjon.

**Comment by lillesand** [comment]
Enig i det. Legger det høyt oppe på lista over ting vi skal gjøre 👍

**Comment by lillesand** [comment]
Lagt inn et utkast her: https://github.com/digipost/signature-api-specification/pull/44. Mulig det kommer mer etterhvert.

**Comment by lillesand** [comment]
Anser denne som løst gjennom #44 og lukker den, så åpner vi heller en ny hvis det er noe som mangler.
