### ISSUE TITLE
Støtte for signering av flere dokumenter samtidig

### ISSUE THREAD

**Issue by eriklian** [digipost/signature-api-specification#51]
Hei,
er det mulighet for eller planer om å støtte signering av flere dokumenter samtidig?

**Comment by MartinBekkelund** [comment]
Hei Erik,

Det stemmer som du skriver at vi ikke støtter multidokument for øyeblikket.

Har du anledning til å utdype behovet og bruksmønsteret litt mer i detalj?

Hvis du ikke vil ta diskusjonen her på GitHub er du hjertelig velkommen til å ta kontakt direkte med meg her --> http://mrtn.at/posten 


Med vennlig hilsen

Martin Koksrud Bekkelund
Direktør for produkt- og forretningsutvikling
Posten Norge AS

**Comment by eriklian** [comment]
Takk for kjapt svar, har sendt deg en epost. Lukker saken her.
