### ISSUE TITLE
Uklarhet rundt signering med BankID på mobil

### ISSUE THREAD

**Issue by trygveaa** [digipost/signature-api-specification#53]
Hei. Jeg lurer på om det er mulig å signere med BankID på mobil gjennom dette APIet. Jeg ser ikke ut til å få opp dette valget i testløsningen hvertfall.

Når jeg kommer til signeringsløsningen via dette APIet (dvs. på https://difitest.signering.posten.no/, jeg har kun testet i testløsningen) står det nederst:

> De fleste BankID på mobil-brukere kan benytte BankID på mobil som erstatning for kodebrikken når de signerer med ordinær BankID. Mer informasjon om BankID på mobil

Bruksanvisningen der sier at man skal trykke på den blå pilen øverst til venstre, men denne mangler. Derimot på https://signering.posten.no/#/logginn/privat/bankid ser jeg at denne pilen er der. Hva er grunnen til at denne mangler på https://difitest.signering.posten.no/?

Jeg ser også at hvis jeg går til https://signering.posten.no/#/logginn og velger «Et dokument fra det offentlige» kan jeg velge BankID på mobil, mens på privat må jeg som nevnt over velge BankID og deretter gå tilbake med pilen, som var litt uintuitivt. Jeg ser det står dette på https://signering.posten.no/#/logginn/privat som jeg er litt usikker på hva dere egentlig mener med.

> BankID på mobil, MinID og Commfides støttes foreløpig ikke for signering. De fleste BankID på mobil-brukere kan likevel benytte BankID på mobil som erstatning for kodebrikken når de signerer med ordinær BankID.

**Comment by trygveaa** [comment]
Ah, nå tror jeg kanskje jeg skjønner hva som skjer. Jeg ser at hvis jeg prøver med test-fødselsnummeret på https://signering.posten.no/#/logginn/privat/bankid får jeg heller ikke opp noen pil. Denne kommer kanskje bare opp når fødselsnummeret har BankID på mobil, og ingen av fødselsnumrene jeg har forsøkt har dette aktivert i testløsningen?

Det som menes med det siste sitatet over er kanskje at på signering for offentlige går dere direkte mot BankID på mobil som en egen tjeneste, mens for private er det BankID integrasjonen selv som håndterer at det er mobil som er benyttet uten at det er noen forskjell for dere? Og det er derfor man først må velge BankID og deretter velge mobil inni denne løsningen? Dette kunne gjerne vært dokumentert i litt mer detalj.

**Comment by fredva** [comment]
Hei Trygve.

_Ang. ditt første spørsmål_: Det er riktig som du sier at fødselsnummeret må ha BankID på mobil for at det skal trigges en dialog for BankID på mobil i BankID-vinduet. `difitest.signering.posten.no` går for øvrig mot preprod-miljøet til BankID, og har derfor et annet sett med brukere. Ditt eget fødselsnummer vil ikke fungere her.

_Ang. ditt andre spørsmål_:
Det er en forskjell på hvilke elektroniske ID-er som støttes for henholdsvis innlogging i signeringsportalen og selve signeringen. 
- Skal du signere et dokument du har mottatt fra en _privat virksomhet_, kan du logge inn med BankID og Buypass. Her kan man også benytte BankID på mobil "inline" i BankID-flyten. 
- Skal du signere et dokument du har mottatt fra en _offentlig virksomhet_, kan du logge inn med ID-porten, og benytte deg av alle innloggingsalternativene der, unntatt MinID. Her kan du altså logge inn med BankID på mobil som en egen tjeneste.

Selve signeringen fungerer likt for både private og offentlige signeringsoppdrag. Her støttes kun BankID og Buypass, men igjen kan man benytte BankID på mobil "inline" i BankID. 

Spør bare om du lurer på noe mer.

Mvh,
Fredrik Valdmanis
Utvikler Posten signering
