### ISSUE TITLE
Problemer med signering i Safari på OS X og iOS

### ISSUE THREAD

**Issue by trygveaa** [digipost/signature-api-specification#55]
Hei. Vi har problemer med signering i Safari på OS X og iOS i testløsningen. Etter vi kommer til signeringsløsningen (på https://difitest.signering.posten.no/) og velger BankID får vi denne feilen:

> Lukk alle nettlesere og prøv igjen om 10 minutter.
> 
> Dersom feilen vedvarer, ta kontakt med banken som har utstedt din BankID, og oppgi følgende kode: BID-2031.

Jeg ser at BID-2031 sier at man må oppdatere nettleser eller operativsystem, men nyeste versjon benyttes. Dette er versjonene som er brukt:

OS X: `10.11.6 (15G1004)` med Safari `9.1.3 (11601.7.8)`
iOS: `10.1.1` med Safari `602.1`

I for eksempel Chrome fungerer derimot signeringen fint.

**Comment by SindreNordbo** [comment]
Hei,

takk for at du gjør oss oppmerksomme på dette.

Jeg ser også `BID-2031` ved signering i Safari på OS X i testmiljøet.
Jeg har imidlertid verifisert at det fungerer i produksjonsmiljøet – dette får meg til å mistenke at det kan være en feil i testmiljøet til BankID.

Vi sjekker opp mot BankID om det er en kjent feil hos de – inntil videre håper jeg det er OK for dere å gjennomføre signeringer med Chrome eller en annen nettleser.

Vennlig hilsen,
Sindre
Utvikler Posten signering

**Comment by trygveaa** [comment]
> Vi sjekker opp mot BankID om det er en kjent feil hos de – inntil videre håper jeg det er OK for dere å gjennomføre signeringer med Chrome eller en annen nettleser.

Takk. Det går fint.

**Comment by SindreNordbo** [comment]
Hei igjen,

antagelsen min om at det var en feil hos BankID var visst ikke riktig :)

Grunnen til at det ikke fungerer i testmiljøet er at Safari som standard ikke tillater tredjepartscookies. Feilen vil ikke dukke opp i produksjon fordi den tekniske løsningen skiller seg noe mellom disse miljøene slik at det ikke er behov for tredjepartscookies i produksjon.

Du kan dermed enten tillate tredjepartscookies i Safari (`Preferences > Privacy > Cookies and website data > Always allow`) eller fortsette å bruke en annen nettleser.
Jeg fant ingen mulighet for å bare tillate tredjepartscookies i Safari for visse domener, så det ser dessverre ut til at du må tillate det for alle nettsider for at det skal fungere i signeringstjenesten.

Vennlig hilsen,
Sindre
Utvikler Posten signering

**Comment by anderslysne** [comment]
Hei! 

Vet dette er et gammelt issue, men lurer på om det fortsatt er tilfellet at signering i test-miljøet ikke fungerer i Safari uten å tillate 3.parts cookies.

Når vi forsøker å signere gjennom Safari får vi feilmeldingen:
"The documents you requested are no longer available. This may happen if you used a link from an old E-mail, or if the documents are already processed. If you think you should have access to these documents, you should contact customer service."

Dersom vi tillater cross-site tracking fungerer det i safari også (Safari -> Preferences -> Privacy ->Prevent cross-site tracking)

Dette virker som det samme problemet beskrevet overnfor, men hadde vært fint å få bekrefet at det fungerer i prod uten å måtte tillate 3. parts cookies

Anders
