### ISSUE TITLE
UNEXPECTED_SERVER_ERROR ved redirect til signeringsportalen

### ISSUE THREAD

**Issue by hfriedrich** [digipost/signature-api-specification#58]
Etter oppretting av et signeringsoppdrag oppstår det en UNEXPECTED_SERVER_ERROR ved redirect til https://difitest.signering.posten.no/signere/. Noen av feil-id'ene er 3FCEA24061040840 og 3FD81D9E61385B88.

**Comment by runeflobakk** [comment]
Hei,

URLene vi får fra dere for `completion_url`, `rejection_url` og `error_url` inneholder alle `requestId=${requestId}` som ser ut som noe som ikke har blitt substituert riktig hos dere?

Feilen hos oss kommer av vår URL-bygger også gjenkjenner dette som en substituerings-fragment, og krasjer fordi vi ikke angir noen `requestId` til vår "URL-bygger" når vi skal bygge URLen for redirect tilbake til dere etter utført signering.

**Comment by hfriedrich** [comment]
Takk for rask svar.

Jeg endret URL'ene og nå fungerer redirecten.

Hadde det vært en idé at det returneres en mer tydelig feilmelding om at en URL har et ugyldig format?

**Comment by runeflobakk** [comment]
Ja, dette er noe vi vurderer om vi skal legge på som "ekstra" validering av URLene ved opprettelse av jobben. En URL som inneholder `${xyz}` er ikke per definisjon syntaks-ugyldig, så vi har ikke hatt dette som en issue før nå.

Takk for heads-up!
