### ISSUE TITLE
Direkte signering polling vs callback

### ISSUE THREAD

**Issue by talisker77** [digipost/signature-api-specification#63]
I dokumentasjonen går det ikke tydelig frem hva som skjer hvis man:

1. oppretter et synkront oppdrag med WaitForCallback
2. oppretter et synkront oppdrag med Polling
3. kjører callback på oppdrag 1

vil ```Proxy.GetStatusChange()``` returnere status på oppdrag 1 (som er spesifisert med ```WaitForCallback```), eller vil den bare returnere eventuell status på 2 (og andre oppdrag som er definert med ```Polling```)?

```
public enum StatusRetrievalMethods
 {
            WaitForCallback = 0,
            Polling = 1
 }
```

**Comment by SindreNordbo** [comment]
Hei,

Bruker du klientbiblioteket for [.NET](https://github.com/digipost/signature-api-client-dotnet) eller [Java](https://github.com/digipost/signature-api-client-java), eller integrerer du direkte?

Uansett – når du gjør det generelle kallet til tjenesten for å hente ut statusendringer uten å angi for hvilket oppdrag vil du kun få respons om de oppdragene som ble opprettet med `StatusRetrievalMethod = Polling`.

For å hente status til oppdrag med `WaitForCallback` må du alltid angi `status_query_token` [som dokumentert](https://github.com/digipost/signature-api-specification#steg-3-hent-status).

**Comment by talisker77** [comment]
Hei, 

Vi bruker .NET klientbiblioteket. 
Takk for svar og det gir et godt svar.

Grunnet til spørsmålet var tekst fra release notes: 

Fra pkt Polling på synkrone [oppdrag](https://github.com/digipost/signature-api-specification/blob/master/doc/release-notes.md#2016-06-22--polling-på-synkrone-oppdrag): 

> På samme måte som i det asynkrone APIet vil klienten tolke alle statuser som returneres (alle åpne synkrone oppdrag) og markere hvilke statuser som er ferdigprosessert før referansen i statusresponsen brukes til å hente det signerte dokumentet.

**Comment by SindreNordbo** [comment]
Skjønner, kan være enig i at det var litt upresist formulert. Bakgrunnen for den litt vage formuleringen er nok at det erfaringsmessig ikke er så mange klienter som benytter seg av både polling- og callback-mekanismen for synkrone oppdrag om hverandre. Skal se om vi kan få tydeliggjort oppførselen litt bedre i dokumentasjonen :)
