### ISSUE TITLE
'Angitt sertifikat [...] kan ikke eksporteres'

### ISSUE THREAD

**Issue by tormodfikse** [digipost/signature-api-specification#64]
Følgende feilmelding returneres, tilsynelatende fordi virksomhetssertifikatet er installert uten "Mark this key as exportable":

"exceptionMessage": "Angitt sertifikat med fingeravtrykk [...] kan ikke eksporteres. Det er nødvendig når sertifikatet ikke er opprettet med 'Microsoft Enhanced RSA and AES Cryptographic Provider' som CryptoAPI provider name (-sp parameter i makecert.exe eller -csp parameter i openssl).",

**Comment by asjafjell** [comment]
Hei, @tormodfikse!

Dette har vi ikke funnet noen vei rundt. Det må kunne eksporteres hvis det skal lastes fra Certificate Store på Windows. Hvis dette ikke er noe dere ønsker å tillate så kan dere bare laste sertifikatet med konstruktør som tar inn `X509Certificate2` direkte, men da må dere selv sørge for sikker håndtering av sertifikat og tilhørende passord.

Siden du jobber med dotnet-klienten til Posten signering, så skal issues postes i [digipost/signature-api-client-dotnet](https://github.com/digipost/signature-api-client-dotnet).

**Comment by asjafjell** [comment]
Fant forresten ut at du jobber med klientbiblioteket for digipost, så da er det ikke her du skal poste, men [Digipost API Client](https://github.com/digipost/digipost-api-client-dotnet)

**Comment by eriklian** [comment]
Hei, vi har hatt samme utfordring i vårt prosjekt, der kunden ikke tillater å installere den private nøkkelen som eksporterbar.
Løsningen for oss er å installere sertifikatet (fra Buypass, .pfx) med kommandoen
`certutil -p <password> -csp "Microsoft Enhanced RSA and AES Cryptographic Provider" -importpfx <filename> NoExport,AT_SIGNATURE`. Sertifikatet blir da installert i Certificate Store uten mulighet for å eksportere den private nøkkelen og slik at .Net-klienten kan bruke det.

**Comment by asjafjell** [comment]
Dette er aboslutt veldig interessant! Vi har sett på måter å komme rundt dette på og fant ut at det ikke var mulig vha kommandolinje. Dere har altså testet dette og det fungerer helt fint?

**Comment by eriklian** [comment]
Ja, vi testet dette på oppfordring fra Buypass. Det fungerte fint med test-sertifikat i testmiljøet. Har ikke installert i produksjon ennå.

**Comment by tormodfikse** [comment]
Vi har også prøvd å gjøre det på denne måten, og har i hvert fall en kunde i drift der denne løsningen fungerer. (Jeg har også hørt om tilfeller der det ikke har fungert, men har ikke nok innsikt i det til å vite hvorfor.)

**Comment by asjafjell** [comment]
Legger infoen i dokumentasjon av biblioteket. Takk for info @eriklian og @tormodfikse!
