### ISSUE TITLE
Stateless flyt for synkrone oppdrag?

### ISSUE THREAD

**Issue by ivarref** [digipost/signature-api-specification#78]
Hei, og takk for eg god tjeneste!

Etter det jeg skjønner så må man ta vare på state for å hente PAdES under synkrone oppdrag.
Altså man må ta vare på `status_url` når man oppretter signeringsoppdraget, for å så bruke `status_url` på nytt når oppdraget er signert og bruker returnert til egen portal.

Hadde det vært mulig å slippe å ta vare på state? Kan redirect URL få både `status_query_token` og `status_url`? Jeg antar at `status_url` er beskyttet av sertifikater, så jeg antar det ikke er en sikkerhetsrisiko å sende begge tilbake?
Eller har jeg gått glipp av noe, og er dette mulig på noen annen måte med deres API?

Takk for svar,
Venlig hilsen
Ivar Refsdal

**Comment by SindreNordbo** [comment]
Hei!

Det stemmer som du sier, at du må ta vare på tilstand for å hente ned PAdES under synkrone oppdrag. Tjenesten er i utgangspunktet ikke designet for tilstandsløse integrasjoner, men det burde ikke være noen tekniske eller sikkerhetsmessige show-stoppere for å sende med `status_url`-en tilbake til avsenderens portal. Det har vært oppe til diskusjon tidligere, men har ikke blitt prioritert fordi det ikke har vært etterspurt av spesielt mange.
Er dette viktig for dere, eller hadde det bare vært en convenience å slippe å ta vare på `status_url`-en?

Et alternativ (som ikke er spesielt godt dokumentert) er å polle på oppdateringer tilsvarende som for asynkrone oppdrag. Ved opprettelsen av et synkront oppdrag setter du i så fall `status-retrieval-method` til `POLLING` på requesten. Deretter kan du polle jevnlig mot tjenesten vår for å se om noen signeringsoppdrag har endret tilstand. Du kan lese mer om polle-mekanismen for asynkrone oppdrag [i dokumentasjonen](https://github.com/digipost/signature-api-specification/blob/master/integrasjon/asynkron.md#steg-2-polling-p%C3%A5-status). Det vil være noen avvik fra tilsvarende mekanisme for synkrone oppdrag (pathen man poller mot er bl. a. litt annerledes), men i det store og hele vil integrasjonsmønsteret være likt.

**Comment by ivarref** [comment]
Hallo, og takk for raskt svar!

Vel, det ville gjort ting enklere å slippe å ha ekstra tilstand. Mindre tilstand betyr som oftest mindre problemer og feil. Om det ikke er en stor sak å legge dette til, så hadde det vært veldig fint å få det inn.
F.eks. slipper man server-side tilstand med f.eks. OAuth 2.0 og JWT. Å unngå (unødvendig) state på server er helt klart noe man bør etterstrebe, etter min mening. Da kan state/DB heller være valgfritt, og ikke påkrevd.

Takk for tipset om polling. Men jeg ser ikke at det løser problemet på en god måte for en synkron flyt ettersom polling gir deg en hvilken som helst jobb.

Den eneste (litt rare) muligheten jeg ser er å angi f.eks. en uuid som del av `exit url` og så spesifisere kønavn som denne `uuid`-en, og deretter gjøre polling på uuid-køen ved retur. Var det dette du mente? Og er dette anbefalt bruk? Det slår meg som en litt tvilsom hack.

**Comment by ivarref** [comment]
Hallo igjen. Har dere kommet fram til noe her?

**Comment by SindreNordbo** [comment]
Hei. Inntil videre har vi besluttet å ikke gjøre denne endringa. Vi har imidlertid notert oss ønsket, og hvis det viser seg at flere avsendere er interessert i dette vil vi ta opp tråden igjen.
